# Generated by Django 6.0 on 2025-12-16 06:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("website_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "companies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyFunding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value_usd", models.DecimalField(decimal_places=2, max_digits=20)),
                ("year", models.IntegerField()),
                ("source_url", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_records",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_funding",
                "ordering": ["-year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyNetworth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value_usd", models.DecimalField(decimal_places=2, max_digits=20)),
                ("year", models.IntegerField()),
                ("source_url", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="networth_records",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_networth",
                "ordering": ["-year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyUsers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.BigIntegerField()),
                ("year", models.IntegerField()),
                ("source_url", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_records",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Users",
                "verbose_name_plural": "Company Users",
                "db_table": "company_users",
                "ordering": ["-year", "-created_at"],
            },
        ),
    ]
